### ISSUE TITLE
"Hidden Power" set value string error

### ISSUE THREAD

**Issue by krynxe** [Jdaco/stadium#1]
When setting the value of a move directly (middle column, pressing enter and typing it), most invalid strings return "Move not found" however entering "Hidden Power" will cause a crash. Note that typing "Hidden Power(bug)" or another type will work properly.

Suggestion: Implement Hidden Power as a single move rather than 16, and have an option in the middle column which simply lets you view the current hidden power type or set a new type (which will adjust the stats accordingly)

**Comment by Jdaco** [comment]
This has been fixed in commit [2539439](https://github.com/Jdaco/stadium/commit/2539439a47eae5f2126557add72ae155dce67457)

**Comment by Jdaco** [comment]
Added hidden power selection in commit [30f3288](https://github.com/Jdaco/stadium/commit/30f3288e901e45f72ad80619fe55665679fd3136)
