### ISSUE TITLE
Menu Controls (minor)

### ISSUE THREAD

**Issue by krynxe** [Jdaco/stadium#2]
Arrow key usage should either be removed, or implemented to match the standard hjkl control scheme. (Arrow keys don't update the pointer position correctly made evident when switching back and forth between control schemes, nor does it update the red text highlighting properly)

**Comment by Jdaco** [comment]
Fixed in commit [c45d3aa](https://github.com/Jdaco/stadium/commit/c45d3aa9413eda1433e6e40aecf24fa917a4566f)

You'll also need to get the latest from https://github.com/Jdaco/urwidgets
