### ISSUE TITLE
Parsing bugs, etc

### ISSUE THREAD

**Issue by krynxe** [Jdaco/stadium#4]
Allowed range of input for stat exp is 0 to 65791 (0x100FF) instead of expected 0 to 65535 (0xFFFF). Going over the max of 0xFFFF weirdly drops that stat by a large amount likely due to the algorithm only taking in 4 bytes. (Either way, user input should stay within 4 bytes of data)

All of the values in the middle column need to have input parsing for settings values manually. Crashes occur from invalid inputs, overflow, etc

**Comment by Jdaco** [comment]
I've set validation for minimum and maximum values for DVs, Level, and Happiness.

Are you saying that the max for stat exp should be 0x100FF instead of 0xFFFF?

**Comment by krynxe** [comment]
No, I'm saying that it allowed input up to 0x100FF, anything beyond that caused a crash, but anything from 0xFFFF - 0x100FF were invalid inputs that were considered valid inputs by the module.

Stat exp should range from 0x0000 - 0xFFFF

**Comment by Jdaco** [comment]
Alright I get it. This is fixed in commit [e058783](https://github.com/Jdaco/stadium/commit/e058783275e667bf74185f38e4c12bc71b94eb7c)

Giving invalid integers gives status "Invalid Value" and setting out of range integers sets to the minimum or maximum
